# Generated by Django 2.0.1 on 2018-01-18 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashtype', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('createddatetime', models.DateTimeField(auto_now_add=True)),
                ('cashtype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Cashtype')),
            ],
        ),
        migrations.CreateModel(
            name='Moneyinout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneyinout', models.TextField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='money',
            name='moneyinout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Moneyinout'),
        ),
        migrations.AddField(
            model_name='money',
            name='parentmoney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Money'),
        ),
        migrations.AddField(
            model_name='money',
            name='relateduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
