# Generated by Django 2.0.1 on 2018-01-19 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0004_inheritor_socialid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='parentmoney',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Money'),
            preserve_default=False,
        ),
    ]
