# Generated by Django 2.0.1 on 2018-01-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0005_auto_20180119_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='parentmoney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Money'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='inheritor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Inheritor'),
        ),
    ]
