# Generated by Django 2.0.1 on 2018-01-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0006_auto_20180119_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=99, max_digits=20),
        ),
    ]
