# Generated by Django 2.0.1 on 2018-01-26 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0007_auto_20180126_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='moneyinout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Moneyinout'),
        ),
    ]
