# Generated by Django 2.0.1 on 2018-01-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0008_auto_20180126_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
