# Generated by Django 2.0.1 on 2018-01-27 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0009_auto_20180126_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='cashtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Cashtype'),
        ),
    ]
