# Generated by Django 2.0.1 on 2018-01-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0012_auto_20180128_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='id',
            new_name='id1',
        ),
    ]
