# Generated by Django 2.0.1 on 2018-01-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0013_auto_20180128_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='id1',
            new_name='id',
        ),
    ]
