# Generated by Django 2.0.1 on 2018-01-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0015_auto_20180128_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=20)),
            ],
        ),
    ]
