# Generated by Django 2.0.1 on 2018-01-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0016_testinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=20)),
            ],
        ),
    ]
