# Generated by Django 2.0.1 on 2018-01-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0017_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('test', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
        migrations.DeleteModel(
            name='Testinfo',
        ),
    ]
