# Generated by Django 2.0.1 on 2018-01-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0018_auto_20180128_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T2',
        ),
    ]
