# Generated by Django 2.0.1 on 2018-01-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0019_delete_t2'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='beneficiarydesignated',
            field=models.BooleanField(default=False),
        ),
    ]
