# Generated by Django 2.0.1 on 2018-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0020_money_beneficiarydesignated'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='donatordesignated',
            field=models.BooleanField(default=False),
        ),
    ]
