# Generated by Django 2.0.1 on 2018-02-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0021_money_donatordesignated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=20)),
                ('moneyinout', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Moneyinout')),
            ],
        ),
        migrations.RemoveField(
            model_name='money',
            name='moneyinout',
        ),
        migrations.RemoveField(
            model_name='money',
            name='test',
        ),
        migrations.AddField(
            model_name='money',
            name='purpose',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Purpose'),
        ),
    ]
