# Generated by Django 2.0.1 on 2018-02-24 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lr', '0022_auto_20180209_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneynode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('sessionid', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('cort', models.CharField(blank=True, max_length=200)),
                ('cashtype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Cashtype')),
                ('parentmoney', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Moneynode')),
                ('purpose', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Purpose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
