# Generated by Django 2.0.1 on 2018-02-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0023_moneynode'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneynode',
            name='money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_money', to='lr.Money'),
        ),
        migrations.AlterField(
            model_name='moneynode',
            name='parentmoney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_money', to='lr.Money'),
        ),
    ]
