# Generated by Django 2.0.1 on 2018-02-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0025_auto_20180225_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='parentmoney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lr.Money'),
        ),
    ]
