# Generated by Django 2.0.1 on 2018-02-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0026_auto_20180225_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneynode',
            name='money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_money', to='lr.Money'),
        ),
        migrations.AlterField(
            model_name='moneynode',
            name='parentmoney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_money', to='lr.Money'),
        ),
    ]
