# Generated by Django 2.0.3 on 2018-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0027_auto_20180227_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wechatreplymsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=50)),
                ('replymsg', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
