# Generated by Django 2.0.3 on 2018-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr', '0028_wechatreplymsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatreplymsg',
            name='replymsg',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
